### ISSUE TITLE
No standardized way to relate objects across files

### ISSUE THREAD

**Issue by carl3** [usnistgov/ElectionResultsReporting#1]
**Organization Name**: Carl Hage

**Organization Type**: 4

**Document**: SP1500-100 ElectionResultsReporting

**Reference**: 4.2.13 ExternalIdentifiers

**Comment**: The objectID used to reference objects within an XML file is not defined to be valid except within the particular version of a particular file. In order to relate objects across files, across versions, and interoperate with existing voting data files and filings, a persistent ID is required (across an election).

In practice, the name associated with an object is typically abbreviated, spelled in different ways in different files, is not always unique (the same name/title occurs for different objects), and is not machine parsable without a complex set of manually-configured, locality-specific pattern matching and correction rules. So the name can't be used to identify an object.

An ID assigned by the Election Authority is often used in official filings, reports, and data files. In general the EA-ID is used to identify objects with the EA EMS and reports. The NIST voting CDFs need to interoperate with files from an EA EMS and interoperate with official filings.

**Suggested Change**: Make `<ExternalIdentifiers>` a required field and indicate that it is to be used to represent a persistent ID across an election cycle. Also IDs assigned by an Election Authority must be preserved in this element.

**Comment by johnpwack** [comment]
While it would be best if everyone used external identifiers, requiring it in the schema may not be appropriate - some types of results reports such as highly aggregated official results don't necessarily need identifiers.  The WG decided not to require them, but I do think that validation tooling should check for their usage and warn users if they are not used.

**Comment by jdmgoogle** [comment]
> Make <ExternalIdentifiers> a required field and indicate that it is to be used to represent a persistent ID across an election cycle. Also IDs assigned by an Election Authority must be preserved in this element.

These don't always exist, especially for people or contests. Geographic locations are more likely to have them, but even then there are election scopes which are one-offs tied to a particular election (e.g., many special districts in California, or cases where two districts are voting to merge into one district). We cannot require a jurisdiction to provide data which it doesn't have, and we don't want to encourage jurisdictions to put useless information in a field just to make the file pass schema validation.

**Comment by jungshadow** [comment]
@carl3 I'd like to support this, but @jdmgoogle took the words out of my mouth: "These don't always exist..." I like @johnpwack's suggestion regarding making it a warning. In other open data initiatives I've been involved in, this has been a first step in making election officials aware of the placeholders and gives them time to plan to incorporate it. Once there's a critical mass of jurisdictions that can supply the data, we can look at hardening the requirements then.

I'd like to make a motion to put this in a "Revisit Later" (or something) label. Maybe collect similar "Revisit Later" issues into a milestone with a date to revisit in about year (depending on how adoption's going)?

**Comment by carl3** [comment]
Perhaps a good solution is to keep it optional, but include a usage note with the definition of `<ExternalIdentifiers>`, explaining it's usage, i.e. the objectId cannot be used outside of a single file, so an ExternalIdentifier is needed to match objects across files, including source files within the EMS of an Election Admin.

I just read the CVR requirements: it mentions there must be one of a set of options to identify contests and candidates, and "Code". What is "Code"?

**Comment by jdmgoogle** [comment]
@carl3 I agree about better documentation explaining the purpose of `objectId` versus `ExternalIdentifiers`.

I don't know about "Code". Earlier versions of the 1500-100 spec used `Code` as the name for what eventually became `ExternalIdentifiers`. Maybe @johnpwack knows more?

**Comment by jungshadow** [comment]
@carl3 This could be a simple lack of coordination between the CVR and ENRR specifications, assuming both elements (i.e. `Code` and `ExternalIdentifiers`) mean the same thing, but I honestly don't know enough about the CVR standard (I'm not part of that group...@johnpwack?). Since this sounds more like a question about [the CVR standard](https://github.com/usnistgov/CastVoteRecords), you may get a better response by leaving an issue about it there.

**Comment by johnpwack** [comment]
My apologies for taking so long to reply.  Yes, Jared is right - I have not finished the documentation for the CVR spec and <Code> will become <ExternalIdentifiers>.  The 1500-100 spec does a decent job of explaining the use of objectId; I have been copying this material to other specs that use objectId as well as other elements from that spec.

**Comment by johnpwack** [comment]
Ooops - I garbled up that message - Code will become ExternalIdentifiers.  Carl, ExternalIdentifiers and use of objectId is explained in the 1500-100 spec; is there a specific issue you have with that documentation?
