### ISSUE TITLE
Increase size of ShortString to 24 characters

### ISSUE THREAD

**Issue by markcwal-google** [usnistgov/ElectionResultsReporting#10]
ShortString is specified as the type for "AnnotatedString", and is currently limited to 16 characters.  This can be limiting for supporting annotations in some non-English languages, specifically German.  Removing the limitation entirely may lead to using the field for purposes outside of its intended function, but it may be helpful to expand the max size to 24 (or even 32) characters.

**Comment by johnpwack** [comment]
Making it 32 is easy to do, no problem.

**Comment by johnpwack** [comment]
I have added this change as well as adding Round to VoteCounts and "recall" to BallotMeasureType.

**Comment by johnpwack** [comment]
Add, will upload new version.
