### ISSUE TITLE
Add <ExternalIdentifiers> to <Person> object.

### ISSUE THREAD

**Issue by markcwal-google** [usnistgov/ElectionResultsReporting#11]
For similar applications that "ExternalIdentifiers" is used for "Candidate", "Party", "Office", etc, it would be useful to have "ExternalIdentifiers" be a property of "Person" as well.  While "Candidate" already has this field, "Person" can represent election officials and party leaders as well.

**Comment by johnpwack** [comment]
For reasons I can't remember, it was already added to Person.  We removed the wrapper element so it's now just ExternalIdentifier.

**Comment by markcwal-google** [comment]
Sorry about that -- I was checking the v1 schema -- I should have checked v2. Thanks!
