### ISSUE TITLE
adding additional filtering to OtherCounts

### ISSUE THREAD

**Issue by johnpwack** [usnistgov/ElectionResultsReporting#15]
I'm thinking that instead of moving CountItemType and DeviceClass filtering elements to OtherCounts, just remove the association with GpUnit, and make OtherCounts a subclass of Counts.  This adds the IsSuppressedForPrivacy boolean, I don't know whether one would ever suppress the number of, say, overvotes for privacy reasons, but it's an optional item.  Comments?

**Comment by carl3** [comment]
John, I think you have to do that-- it just puts it back to 1.0 with a name change (no problem calling it OtherCounts). Often results are reported separately by precinct-ballots, mail-ballots, and total ballots. These include UnderVotes and OverVotes. So you need the CountItemType from the base class. As far as I know, what was in V1.0 was fine.

Detailed reports do the same with separate precinct and mail ballots, but give precinct subtotals (the GpUnit associated with the <Counts> is a precinct). Making OtherCounts a subclass of Counts works for all cases.

**Comment by johnpwack** [comment]
All - I'll make OtherCounts a subclass of Counts today unless I hear objections.
