### ISSUE TITLE
Election Type enumerations and definitions do not match VVSG glossary

### ISSUE THREAD

**Issue by whittsxnbq** [usnistgov/ElectionResultsReporting#25]
The enumerations for Election Type, and the definitions of those types, do not match the new VVSG glossary.  The glossary contains slightly different types, and in some cases such as General Election the definitions directly conflict.  the VVSG Glossary definitions are more correct.  Can we harmonize these?  Otherwise there will be confusion in how to interpret the data provided in the feed.  For example, if General Election is only for the election which takes place in November of even numbered years (based on the definition in 1500-100 v2), then any scheduled non-primary election that is not within that timeframe would be an Other Type.  if we use the VVSG definition which is more broad, then any scheduled non-primary is a "general".  We need to have this resolved so we know how to correctly interpret and report this field in our 1500-100 feed.

**Comment by johnpwack** [comment]
Thanks for the catch.  I synced up with the glossary terms and the latest version is now on the server.  Can I close this thread?

**Comment by whittsxnbq** [comment]
I'm looking at the word doc dated 12/8/2018.  General Election is fixed but Open Primary, Closed Primary and Partisan Primary are still not quite right.  I checked the glossary and I don't think they are quite right there either.  I reported the glossary issues to Katy.  Once she responds and we have those fixed in the glossary, we can update them here.

**Comment by johnpwack** [comment]
I've synced up definitions in 1500-100 V2 with those in the glossary; the most recent version of the spec (2019-02-01) matches up.

**Comment by whittsxnbq** [comment]
HI, I just looked in github, and the word version of the schema documentation still has the wrong definitions.  Can you send me a link to the version on github that has the correct ones?  I need to send the documentation to some people but I want to send them the correct stuff.

**Comment by whittsxnbq** [comment]
More specifically, I’m reviewing the Word version of the documentation called WERB-final dated Feb 1 2019.  If you go to page 102, it lists the Election Type enumeration and the definitions in that chart are still the old ones.

From: Whitt, Sarah - ELECTIONS
Sent: Wednesday, February 13, 2019 2:01 PM
To: usnistgov/ElectionResultsReporting <reply@reply.github.com>; usnistgov/ElectionResultsReporting <ElectionResultsReporting@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [usnistgov/ElectionResultsReporting] Election Type enumerations and definitions do not match VVSG glossary (#25)

HI, I just looked in github, and the word version of the schema documentation still has the wrong definitions.  Can you send me a link to the version on github that has the correct ones?  I need to send the documentation to some people but I want to send them the correct stuff.

**Comment by johnpwack** [comment]
I hope the latest version I uploaded does the trick.  I synced the glossary terms with those in John's living version fo the glossary.  This version also has a few small changes suggested by Jennifer Morrell.

**Comment by whittsxnbq** [comment]
The Word doc for WERB-Final for 2019-02-09 is still wrong on page 102.

**Comment by JDziurlaj** [comment]
Hi John,



I think Sarah is referring to the enumeration `ElectionType` in the UML
Documentation.

**Comment by whittsxnbq** [comment]
I verified that in the Living Glossary on Github has definition for General Election as “Election in which all eligible voters, regardless of party affiliation, are permitted to select candidates to fill public office and/or vote on ballot measures.”

In the WERB-Final version on page 102 where it lists the Election Type enumeration, the definition for General Election says “For the election held typically on the national day for elections (e.g., the Tuesday after the 1st Monday in November).”

Please make the Election Type enumeration definitions match the Living Glossary definitions.

From: Whitt, Sarah - ELECTIONS
Sent: Friday, February 15, 2019 1:20 PM
To: 'usnistgov/ElectionResultsReporting' <reply@reply.github.com>; usnistgov/ElectionResultsReporting <ElectionResultsReporting@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [usnistgov/ElectionResultsReporting] Election Type enumerations and definitions do not match VVSG glossary (#25)

The Word doc for WERB-Final for 2019-02-09 is still wrong on page 102.

**Comment by johnpwack** [comment]
Ok, I missed that it was in the enumeration definition, it is fixed now.  Probably those enumeration values should not be documented as they are; they should point to the glossary definitions.

**Comment by whittsxnbq** [comment]
I have found it very handy to have the definitions within the enumerations.  However I can also see why that would be difficult to synch.  I would recommend that someone check all the enumeration definitions to confirm they match the glossary.  Or else remove them all?

**Comment by whittsxnbq** [comment]
The enumeration definitions I mentioned are now fixed so I am closing this out.
