### ISSUE TITLE
Proposal:  Replace "float" with "double" in the schema

### ISSUE THREAD

**Issue by markcwal-google** [usnistgov/ElectionResultsReporting#26]
"float" is used in three places: Latitude, Longitude, VoteCount.  In all three of these, it would be preferable to use "double" instead.  Latitude/Longitude has already been updated to double in the VIP 5.1 schema, and for VoteCounts, there are problems representing high counts in the millions accurately with only a float

**Comment by johnpwack** [comment]
Mark, my apologies, you are right.  I did change this earlier as you requested; perhaps I never loaded that version.  At any rate, I'm fixing it now and will notify when updated.

**Comment by markcwal-google** [comment]
Okay great -- I couldn't remember if I had suggested this earlier or not so wanted to just make sure that it got flagged

**Comment by johnpwack** [comment]
The model, image, and XML schema are updated on this branch.  Forthcoming will be the JSON schema and the documentation.

**Comment by JDziurlaj** [comment]
Changes in version2.
