### ISSUE TITLE
Errata: Confusion in example for Section 4.2.2

### ISSUE THREAD

**Issue by alanyst** [usnistgov/ElectionResultsReporting#31]
This is in reference to the PDF as of commit ccddf81c52932f6b00db2c294a26d3a3818bc7f6.

The document says the following:
> If a UML attribute has the «xmlAttribute» stereotype or the class contains an attribute with the «simpleContent» stereotype, the attribute becomes an XML attribute. The «simpleType» stereotype indicates that the attribute is the target for the character data of the XML element.

It then gives an example:

> FileValue
> «simpleContent»-Data : base64Binary [1]
> -fileName : String [0..1]
> -mimeType : String [0..1]
> Table: UML Class File

Which it says produces:
> \<FileValue fileName="String"
mimeType="string"\>UjBsR09EbGhjZ0dTQUxNQUFBUUNBRU1tQ1p0dU1GUXhEUzhi\<FileValue\>

(Aside: the XML tag is not properly closed.)

The confusion is that the example contradicts the normative text: is it the «simpleContent» stereotype that indicates the attribute is the target for the character data of the XML element, as the example suggests, or is the example in error and it should say «simpleType» instead?

**Comment by JDziurlaj** [comment]
The `«simpleContent»` stereotype is the correct one to use to indicate the CDATA target. `«simpleType»` is a typo. Thank you for reporting this.

**Comment by johnpwack** [comment]
This is corrected now in the latest version.
