### ISSUE TITLE
Inconsistency between Figure 8 and ElectionResultsReportingV2.png

### ISSUE THREAD

**Issue by sfsinger19103** [usnistgov/ElectionResultsReporting#36]
In [the word doc](https://github.com/usnistgov/ElectionResultsReporting/blob/version2/NIST%201500-100%20ERR%20Specification%20V2.docx) Figure 8 (Simplified UML Class Diagram), an arrow indicates that `GpUnit` is an instance of `ReportingUnit`. In the full UML Diagram (ElectionResultsReportingV2.png), the arrow goes the other way, indicating that `ReportingUnit` is an instance of `GpUnit`. Which is correct?

**Comment by sfsinger19103** [comment]
Text on p. 28 of [the word doc](https://github.com/usnistgov/ElectionResultsReporting/blob/version2/NIST%201500-100%20ERR%20Specification%20V2.docx) indicates that "ReportingUnit is a type of GpUnit".

**Comment by JDziurlaj** [comment]
The arrow of Figure 8 should be reversed.

**Comment by JDziurlaj** [comment]
Fixed in latest special publication.
