### ISSUE TITLE
PrimaryParty arrow is many-valued, but why?

### ISSUE THREAD

**Issue by sfsinger19103** [usnistgov/ElectionResultsReporting#39]
Why is the PrimaryParty arrow from CandidateContest to Party possibly many-valued?

Concretely, consider the US Senator from Oregon. In any year where a seat is open, there are three contests:
Contest for the Republican Party nomination to US Senate (voted at primary)
Contest for the Democratic Party nomination to US Senate (voted at primary)
Contest for the US Senate (voted at general)

It seems to me that (1) and (2) are each associated to one single party, while (3) is associated to no party.

What am I missing?

**Comment by jdmgoogle** [comment]
Unfortunately (but not surprisingly...) primaries in the U.S. are a bit more complicated than that. See [the NCSL page on primary election types](https://www.ncsl.org/research/elections-and-campaigns/primary-types.aspx). Having this feature allows the schema to distinguish between these different varieties.

For example, in an open primary

> voters may choose privately in which primary to vote. In other words, voters may choose which party’s ballot to vote, but this decision is private and does not register the voter with that party.

but in a partially closed system

> state law permits political parties to choose whether to allow unaffiliated voters or voters not registered with the party to participate in their nominating contests before each election cycle.

A spec publisher could create a `Party` element indicating affirmatively-unaffiliated voters. In an open primary, there may not be any `PrimaryPartyIds` associated with a contest, but in a partially open system the candidate contest may have `PrimaryPartyIds` for (a) the party holding the contest, and (b) the `Party` element indicating unaffiliated voters.
