### ISSUE TITLE
Runoff status needed to interpret results (show winners)

### ISSUE THREAD

**Issue by carl3** [usnistgov/ElectionResultsReporting#5]
**Organization Name**: Carl Hage

**Organization Type**: 4

**Document**: SP1500-100 ElectionResultsReporting

**Reference**: 4.2.6 Contest

**Comment**: The `advanced-to-runoff` is available as a post election status, but there is no way to indicate when an election contest can have a runoff or the stage for this contest. The runoff conditions are needed to properly identify candidates that are winning vs a pair (for example) that advance to a runoff.

The `<ElectionType>` has a primary vs general vs runoff that applies to all contests in an election (and commonly used to label an election to the public), but the type can vary by contest.

In theory, the VoteVariation could be extended to include runoff conditions, but gets complex. There seem to be possible runoffs for both a partisan-primary and general, "partisan-primary" meaning a party-only vote, winners per party move to a general election.

A runoff for a single seat contest could be unconditional, i.e. the top two vote getters advance to a primary (even if there are only 2 candidates), or conditional, the runoff is held only if no candidate gets more than 50% of votes cast.

When there are multiple seats elected (vote for n of m), runoff conditions can be more complex. If a candidate gets more votes than 50% of ballots cast, then in a conditional runoff, they win and the runoff applies only to the remaining seats to be filled. (For example if 5 candidates in a city council are elected with "Vote for no more than 5", and 2 candidates receive more votes than 50% of ballots cast, then then runoff elects 3 seats (the runoff might be "Vote for no more than 3"). For vote for n of m candidates, m (the number of candidates in the runoff) could be n+1 or 2*n. [If n is 1 then n+1 is the same as 2*n.]

I do not know if there are more complex conditions for a runoff.

**Suggested Change**: It would be useful to include runoff conditions with an office definition, as well as the conditions in effect for a particular contest in an election.

Rather than having the runoff variation coded as a single enumerated type, it may work better to be able to indicate a set of characteristics. [A repeatable enumerated type, each selected no more than once, and some may be mutually exlusive.] Alternatively, it could be a list of boolean or enumerated types.

The runoff characteristics I can think of are:
  * no runoff
  * is runoff (applies to a contest)
  * is primary runoff (applies to a contest)
  * primary runoff (runoff on partisan primary)
  * general runoff (runoff on general or non primary election)
  
An alternative coded as an enumerated type:
  * Single election
  * partisan primary, general election
  * general election, runoff
  * partisan primary, partisan runoff, general election
  * partisan primary, general election, general runoff
  * partisan primary, partisan runoff, general election

Conditional could be a boolean:
  * unconditional runoff (runoff held independent of votes)
  * conditional runoff (runoff held unless a candidate receives more votes than 50% of valid ballots cast)
  
For n of m voting, the number advancing to a runoff could be a boolean, but possibly better as an extensible enumerated type:
  * n+1 candidates in runoff (n is number elected)
  * 2*n candidates in runoff
  
The at-large/by-district can vary in a runoff:
  * At-large runoff (voters within one district, i.e. portion of a jurisdiction, vote for candidates in a primary, then all voters in the jurisdiction vote in the runoff)
  
A partisan primary/general election can have a nonpartisan runoff (e.g. Judges in Ohio are listed without party affiliation in the runoff.
  * Nonpartisan Runoff
  
Perhaps someone could suggest a convienient way to code this. [In my own system I use an enumerated set of characteristic phrases to describe conditions on an office.]

It is also useful to define when a runoff is to be held-- a date for a contest, or for an office, could be a number of days after an election, or a day of week and day range in a month, e.g. Tuesday November 2-8.

**Comment by jdmgoogle** [comment]
This could easily get more complicated than the entirety of the standards we've created so far. There are lots of other possible conditions or outcomes. E.g., winning not just a majority, but also getting a majority within a majority of the districts; people who cross some threshold get to the runoff, but it can be at most *N* of them.

Broadly speaking I think the pre-election report can indicate the maximum number of people who can advance to a runoff (see usnistgov/Voting#8) but getting into the business logic or representing regional legal requirements is going to be like wading into quicksand.

**Comment by carl3** [comment]
I've only seen 3 kinds of runoff: 1) Conditional runoff held only if the winner doesn't get 50%, 2) Unconditional runoff (top 2 always advance), and 3) (Found only once) A conditional runoff held for council with more than 1 elected-- candidates that didn't get 50% were in a runoff for remaining seats, 2 candidates per seat. [That besides the usual partisan primary and combined general.]

Probably you really only need to indicate 3 options: 1 Conditional Runoff, 2 Unconditional Runoff, and 3 Other with a paragraph of human read rules. Plus a date.

Separate from that is the at-large runoff status, and non-partisan runoff status that defines differences in voting type.

**Comment by jdmgoogle** [comment]
I have seen instances of both examples I provided, each within the last six months.
