### ISSUE TITLE
Typo: xsd has incorrect documentation for ShortString length

### ISSUE THREAD

**Issue by alanyst** [usnistgov/ElectionResultsReporting#55]
In the XSD, the documentation elements for AnnotatedString, AnnotatedUri, and ContactInfo say that ShortString is limited to 16 characters, not the 32 that is in the actual definition. This is at https://github.com/usnistgov/ElectionResultsReporting/blob/version2/NIST_V2_election_results_reporting.xsd in commit 829995c.

**Comment by JDziurlaj** [comment]
Issue reproduced. Documentation needs to be updated in MagicDraw model. 32 characters is the correct data width.
