### ISSUE TITLE
Add `LeaderPersonIds` to `Party`

### ISSUE THREAD

**Issue by jdmgoogle** [usnistgov/ElectionResultsReporting#7]
In the same way that it's useful to have information about who's the election administrator, it's useful to know the leader(s) of a political party. I.e.,

```xml
<xsd:element minOccurs="0" maxOccurs="1" name="LeaderPersonIds" type="xsd:IDREFS">
```

This is useful for when the leader of a political party is not a candidate in that particular election. E.g., the chairs of the [Virginia GOP](https://www.gop.com/leaders/state-chairman-john-whitbeck-va) and [Virginia Democratic](http://vademocrats.org/your-party/chairwoman-susan-swecker/) parties.

**Comment by johnpwack** [comment]
This sounds fine to me.  Sam, could you add this to Party for the version two model?

**Comment by samueldana** [comment]
Sounds good to me. Will do.
